/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import javax.swing.JOptionPane;
import sql.go;

/**
 *
 * @author Mohammad
 */
public class AddMaterial extends javax.swing.JFrame {

    
    go g = new go();
    /**
     * Creates new form AddClinte
     */
    public AddMaterial() {
        initComponents();
        
        fillComboBoxGrop();
        fillComboBoxWarehouse();
    }

    public void fillComboBoxGrop()
    {
        cmbGrop.removeAllItems();
        String sql = "SELECT * FROM grop";
        g.fillCombo(cmbGrop,sql);
    }
    public void fillComboBoxWarehouse()
    {
        cmbWarehouse.removeAllItems();
        String sql = "SELECT * FROM warehouse";
        g.fillCombo(cmbWarehouse,sql);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAddEditItem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cmbGrop = new javax.swing.JComboBox<>();
        cmbWarehouse = new javax.swing.JComboBox<>();
        btnBack1 = new javax.swing.JButton();
        btnBack2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(14, 114, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEditItem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddEditItem.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEditItem.setText("اضافة سلعة جديدة");
        jPanel2.add(lblAddEditItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("اسم السلعة:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 90, 30));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName.setMargin(new java.awt.Insets(2, 2, 2, 5));
        jPanel3.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("النوع :");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 60, 30));

        btnAdd1.setBackground(new java.awt.Color(235, 235, 235));
        btnAdd1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(14, 114, 61));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnAdd1.setText("حفظ");
        btnAdd1.setBorderPainted(false);
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.setFocusable(false);
        btnAdd1.setIconTextGap(8);
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 180, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(" المخزن :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 60, 30));

        cmbGrop.setBackground(new java.awt.Color(254, 255, 255));
        cmbGrop.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbGropFocusGained(evt);
            }
        });
        jPanel3.add(cmbGrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 130, 30));

        cmbWarehouse.setBackground(new java.awt.Color(254, 255, 255));
        cmbWarehouse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbWarehouseFocusGained(evt);
            }
        });
        jPanel3.add(cmbWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 30));

        btnBack1.setBackground(new java.awt.Color(235, 235, 235));
        btnBack1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(14, 114, 61));
        btnBack1.setText("اضافة نوع");
        btnBack1.setBorderPainted(false);
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.setFocusable(false);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 30));

        btnBack2.setBackground(new java.awt.Color(235, 235, 235));
        btnBack2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack2.setForeground(new java.awt.Color(14, 114, 61));
        btnBack2.setText("اضافة مخزن");
        btnBack2.setBorderPainted(false);
        btnBack2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack2.setFocusable(false);
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 120, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 330));

        setSize(new java.awt.Dimension(430, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        
        if(txtName.getText().equals("") && cmbGrop.getItemCount() == 0 && cmbWarehouse.getItemCount() == 0)
        {
            JOptionPane.showMessageDialog(null, "الرجاء ملئ الحقول");
        }
        else
        {
            String name = txtName.getText();
            String type = cmbGrop.getSelectedItem().toString();
            String warehouse = cmbWarehouse.getSelectedItem().toString();

            go g = new go();
            
            String sql1 = "SELECT ID FROM material WHERE Name = '" + name + "'";
            String id = go.getData(sql1);
            if(!id.equals(""))
            {
                JOptionPane.showMessageDialog(null, "هذه السلعة موجودة");
                txtName.setText("");
                txtName.requestFocus();
                return;
            }
            
            String sql = "INSERT INTO material(Name , Price , Quantity , Type , WarehouseName) VALUES "
                    + "('"+ name + "','" + 0 + "','" + 0 +  "','" + type + "','" + warehouse +"')";
            String result = g.query(sql);
            System.out.println(result);
            
            JOptionPane.showMessageDialog(null, "تم الاضافة");
            txtName.setText("");
            cmbGrop.setSelectedIndex(0);
            cmbWarehouse.setSelectedIndex(0);
            txtName.requestFocus();
        } 
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        new AddType().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        new AddWarehouse().setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void cmbGropFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbGropFocusGained
        fillComboBoxGrop();
    }//GEN-LAST:event_cmbGropFocusGained

    private void cmbWarehouseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbWarehouseFocusGained
        fillComboBoxWarehouse();
    }//GEN-LAST:event_cmbWarehouseFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMaterial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JComboBox<String> cmbGrop;
    private javax.swing.JComboBox<String> cmbWarehouse;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblAddEditItem;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
