/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import sql.go;


/**
 *
 * @author Mohammad
 */
public class ClientsAndProvider extends javax.swing.JFrame {

    public String Name = "" ;
    int r = -1;
    go g = new go();
    
    public ClientsAndProvider() {
        initComponents();
        btnClients.setBackground(new Color(14,114,61));
        
        tableHeader(tblClients);
        headerColor(tblClients);
        setCellsAlignment(tblClients, SwingConstants.CENTER);
        
        tableHeader(tblProviders);
        headerColor(tblProviders);
        setCellsAlignment(tblProviders, SwingConstants.CENTER);
        
        txtSearchClients.requestFocus();
        fillTable("SELECT Address, Phone, CONCAT(FORMAT(Debt, 0), ' د.ع') AS 'Debt', Name FROM client WHERE Currency = 'د.ع'", tblClients); 
       
        fillTable("SELECT Address, Phone, CONCAT('$ ', FORMAT(Debt, 0)) AS 'Debt', Name  FROM provider", tblProviders);
        
        btnDelete.setVisible(false);
        btnDelete1.setVisible(false);
    }
    
    void tableHeader(JTable table)
    {
        table.getTableHeader().setReorderingAllowed(false);
        table.setDefaultEditor(Object.class, null);
    }
    
    void headerColor(JTable table)
    {
        JTableHeader header = table.getTableHeader();
        header.setForeground(new Color(14,114,61));
        header.setFont(new Font("Tahoma" , Font.BOLD , 16));
    }
    
    private  void setCellsAlignment(JTable table, int alignment)
    {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(alignment);

        TableModel tableModel = table.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            table.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }
    
    private void fillTable(String sql, JTable table)
    {
        g.fillToJTable(sql, table);
    }
    
    void filter(String query,JTable table)
    {
        DefaultTableModel model= (DefaultTableModel) table.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        table.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        txtSearchClients = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnDelete1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClients = new javax.swing.JTable();
        btnClientsPaid = new javax.swing.JButton();
        btnRefreshClients = new javax.swing.JButton();
        cmbClients = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtSearchProviders = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblProviders = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnProvidersPaid = new javax.swing.JButton();
        btnRefreshProvider = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnClients = new javax.swing.JButton();
        btnProvider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 114, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الزبائن و المزودين");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 180, 30));

        btnBack1.setBackground(new java.awt.Color(235, 235, 235));
        btnBack1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack1.setForeground(new java.awt.Color(14, 114, 61));
        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        btnBack1.setText("الرجوع");
        btnBack1.setBorderPainted(false);
        btnBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack1.setFocusable(false);
        btnBack1.setIconTextGap(8);
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 50));

        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setEnabled(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearchClients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearchClients.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSearchClients.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtSearchClients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchClientsKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 220, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifying-glass.png"))); // NOI18N
        jLabel9.setText("البحث ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 110, 40));

        btnDelete1.setBackground(new java.awt.Color(235, 235, 235));
        btnDelete1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDelete1.setForeground(new java.awt.Color(14, 114, 61));
        btnDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/garbage.png"))); // NOI18N
        btnDelete1.setText("حذف");
        btnDelete1.setBorderPainted(false);
        btnDelete1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete1.setFocusable(false);
        btnDelete1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDelete1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDelete1MouseExited(evt);
            }
        });
        btnDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 160, 40));

        tblClients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "العنوان", "الهاتف", "ديون الزبون", "اسم الزبون"
            }
        ));
        tblClients.setRowHeight(26);
        tblClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClients);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 880, 430));

        btnClientsPaid.setBackground(new java.awt.Color(235, 235, 235));
        btnClientsPaid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnClientsPaid.setForeground(new java.awt.Color(14, 114, 61));
        btnClientsPaid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/commission.png"))); // NOI18N
        btnClientsPaid.setText("تسديد الديون");
        btnClientsPaid.setBorderPainted(false);
        btnClientsPaid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClientsPaid.setFocusable(false);
        btnClientsPaid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientsPaidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientsPaidMouseExited(evt);
            }
        });
        btnClientsPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientsPaidActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientsPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 160, -1));

        btnRefreshClients.setBackground(new java.awt.Color(235, 235, 235));
        btnRefreshClients.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRefreshClients.setForeground(new java.awt.Color(14, 114, 61));
        btnRefreshClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnRefreshClients.setText("تحديث");
        btnRefreshClients.setBorderPainted(false);
        btnRefreshClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshClients.setFocusable(false);
        btnRefreshClients.setIconTextGap(8);
        btnRefreshClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshClientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshClientsMouseExited(evt);
            }
        });
        btnRefreshClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshClientsActionPerformed(evt);
            }
        });
        jPanel2.add(btnRefreshClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, 40));

        cmbClients.setBackground(new java.awt.Color(254, 255, 255));
        cmbClients.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbClients.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "د.ع", "$" }));
        cmbClients.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClientsItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, 50, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("العملة :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 60, 40));

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifying-glass.png"))); // NOI18N
        jLabel8.setText("البحث ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 110, 40));

        txtSearchProviders.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearchProviders.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSearchProviders.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtSearchProviders.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchProvidersKeyReleased(evt);
            }
        });
        jPanel3.add(txtSearchProviders, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 220, 40));

        tblProviders.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblProviders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "العنوان", "الهاتف", "ديون المحل", "اسم المزود"
            }
        ));
        tblProviders.setRowHeight(26);
        tblProviders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProvidersMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblProviders);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 880, 430));

        btnDelete.setBackground(new java.awt.Color(235, 235, 235));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(14, 114, 61));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/garbage.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 160, 40));

        btnProvidersPaid.setBackground(new java.awt.Color(235, 235, 235));
        btnProvidersPaid.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnProvidersPaid.setForeground(new java.awt.Color(14, 114, 61));
        btnProvidersPaid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/commission.png"))); // NOI18N
        btnProvidersPaid.setText("تسديد الديون");
        btnProvidersPaid.setBorderPainted(false);
        btnProvidersPaid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProvidersPaid.setFocusable(false);
        btnProvidersPaid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnProvidersPaidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnProvidersPaidMouseExited(evt);
            }
        });
        btnProvidersPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProvidersPaidActionPerformed(evt);
            }
        });
        jPanel3.add(btnProvidersPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 160, -1));

        btnRefreshProvider.setBackground(new java.awt.Color(235, 235, 235));
        btnRefreshProvider.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRefreshProvider.setForeground(new java.awt.Color(14, 114, 61));
        btnRefreshProvider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnRefreshProvider.setText("تحديث");
        btnRefreshProvider.setBorderPainted(false);
        btnRefreshProvider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshProvider.setFocusable(false);
        btnRefreshProvider.setIconTextGap(8);
        btnRefreshProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRefreshProviderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRefreshProviderMouseExited(evt);
            }
        });
        btnRefreshProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshProviderActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefreshProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, 40));

        jTabbedPane1.addTab("tab2", jPanel3);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 25, 900, 600));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClients.setBackground(new java.awt.Color(245, 245, 245));
        btnClients.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnClients.setForeground(new java.awt.Color(255, 255, 255));
        btnClients.setText("الزبائن");
        btnClients.setBorder(null);
        btnClients.setBorderPainted(false);
        btnClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClients.setFocusable(false);
        btnClients.setIconTextGap(8);
        btnClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClientsMouseClicked(evt);
            }
        });
        jPanel5.add(btnClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 110, 50));

        btnProvider.setBackground(new java.awt.Color(245, 245, 245));
        btnProvider.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnProvider.setForeground(new java.awt.Color(14, 114, 61));
        btnProvider.setText("المزودين");
        btnProvider.setBorderPainted(false);
        btnProvider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProvider.setFocusable(false);
        btnProvider.setIconTextGap(8);
        btnProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProviderMouseClicked(evt);
            }
        });
        jPanel5.add(btnProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 110, 50));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 50, 130, 570));

        setSize(new java.awt.Dimension(1024, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        this.dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseClicked
        btnClients.setBackground(new Color(14,114,61));
        
        btnProvider.setBackground(new Color(245,245,245));
        
        btnClients.setForeground(Color.WHITE);
                
        btnProvider.setForeground(new Color(14,114,61));
        
        jTabbedPane1.setSelectedIndex(0);
        txtSearchClients.requestFocus();
        tblClients.clearSelection();
        Name = "";
    }//GEN-LAST:event_btnClientsMouseClicked

    private void btnProviderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProviderMouseClicked
        btnProvider.setBackground(new Color(14,114,61));
        
        btnClients.setBackground(new Color(245,245,245));
        
        btnProvider.setForeground(Color.WHITE);
                
        btnClients.setForeground(new Color(14,114,61));
        
        jTabbedPane1.setSelectedIndex(1);
        txtSearchProviders.requestFocus();
        tblProviders.clearSelection();
        Name="";
    }//GEN-LAST:event_btnProviderMouseClicked

    private void txtSearchClientsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchClientsKeyReleased
        String query = txtSearchClients.getText();
        filter(query, tblClients);
    }//GEN-LAST:event_txtSearchClientsKeyReleased

    private void tblClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientsMouseClicked
        if(tblClients.getSelectedRow() != -1)
        {
            r = tblClients.getSelectedRow();
            Name = tblClients.getValueAt(r, 3).toString();
        }
        else
        {
            Name = "";
        }
    }//GEN-LAST:event_tblClientsMouseClicked

    private void txtSearchProvidersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchProvidersKeyReleased
        String query = txtSearchProviders.getText();
        filter(query, tblProviders);
    }//GEN-LAST:event_txtSearchProvidersKeyReleased

    private void tblProvidersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProvidersMouseClicked
        if(tblProviders.getSelectedRow() != -1)
        {
            r = tblProviders.getSelectedRow();
            Name = tblProviders.getValueAt(r, 3).toString();
        }
        else
        {
            Name = "";
        }
    }//GEN-LAST:event_tblProvidersMouseClicked

    private void btnDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete1ActionPerformed
//        if(Name.equals(""))
//        {
//            JOptionPane.showMessageDialog(null, "الرجاء تحديد العنصر المراد حذفه");
//        }
//        else
//        {
//           int dialogResult = JOptionPane.showConfirmDialog(null, "هن انت متأكد من حذف هذا العنصر", "انتبه", JOptionPane.YES_NO_OPTION);
//            if(dialogResult == 0)
//            {
//                String sql = "DELETE FROM client WHERE ID ='" + ID + "'";
//                String result = g.query(sql);
//
//                DefaultTableModel model=(DefaultTableModel)tblClients.getModel();
//                model.removeRow(r);
//                tblClients.setModel(model);
//
//                JOptionPane.showMessageDialog(null, "تم الحذف");
//                tblClients.clearSelection();
//                ID = "";
//            }
//            else
//            {
//                tblClients.clearSelection();
//                ID = "";
//            }   
//        }
    }//GEN-LAST:event_btnDelete1ActionPerformed

    private void btnClientsPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsPaidActionPerformed
        if(Name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "الرجاء تحديد الزبون");
        }
        else
        {
            //String name = tblClients.getValueAt(r, 2).toString();
            String debt = tblClients.getValueAt(r, 2).toString();
            new ClientsPaid(Name,debt).setVisible(true);
            Name = "";
        }
    }//GEN-LAST:event_btnClientsPaidActionPerformed

    private void btnDelete1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseEntered
        jTabbedPane1.setEnabled(true);
    }//GEN-LAST:event_btnDelete1MouseEntered

    private void btnDelete1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDelete1MouseExited
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_btnDelete1MouseExited

    private void btnClientsPaidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsPaidMouseEntered
        jTabbedPane1.setEnabled(true);
    }//GEN-LAST:event_btnClientsPaidMouseEntered

    private void btnClientsPaidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsPaidMouseExited
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_btnClientsPaidMouseExited

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        jTabbedPane1.setEnabled(true);
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_btnDeleteMouseExited

    private void btnProvidersPaidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvidersPaidMouseEntered
         jTabbedPane1.setEnabled(true);
    }//GEN-LAST:event_btnProvidersPaidMouseEntered

    private void btnProvidersPaidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvidersPaidMouseExited
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_btnProvidersPaidMouseExited

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//        if(ID.equals(""))
//        {
//            JOptionPane.showMessageDialog(null, "الرجاء تحديد العنصر المراد حذفه");
//        }
//        else
//        {
//           int dialogResult = JOptionPane.showConfirmDialog(null, "هن انت متأكد من حذف هذا العنصر", "انتبه", JOptionPane.YES_NO_OPTION);
//            if(dialogResult == 0)
//            {
//                String sql = "DELETE FROM provider WHERE ID ='" + ID + "'";
//                String result = g.query(sql);
//
//                DefaultTableModel model=(DefaultTableModel)tblProviders.getModel();
//                model.removeRow(r);
//                tblProviders.setModel(model);
//
//                JOptionPane.showMessageDialog(null, "تم الحذف");
//                tblProviders.clearSelection();
//                ID = "";
//            }
//            else
//            {
//                tblProviders.clearSelection();
//                ID = "";
//            }   
//        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshClientsActionPerformed
        String currency = cmbClients.getSelectedItem().toString();
        
        if(currency.equals("د.ع"))
        {
            fillTable("SELECT Address, Phone, CONCAT(FORMAT(Debt, 0), ' د.ع') AS 'Debt', Name FROM client WHERE Currency = 'د.ع'", tblClients); 
        }
        else
        {
             fillTable("SELECT Address, Phone, CONCAT('$ ', FORMAT(Debt, 0)) AS 'Debt', Name FROM client WHERE Currency = '$'", tblClients); 
        }

        //String sql = "SELECT Address, Phone, CONCAT(FORMAT(Debt, 0), ' د.ع') AS 'Debt', Name, ID FROM client";
        //fillTable(sql, tblClients);
        txtSearchClients.requestFocus();
    }//GEN-LAST:event_btnRefreshClientsActionPerformed

    private void btnRefreshProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshProviderActionPerformed
        String sql = "SELECT Address, Phone, CONCAT(FORMAT(Debt, 0), ' د.ع') AS 'Debt', Name, ID  FROM provider";
        fillTable(sql, tblProviders);
        txtSearchProviders.requestFocus();
    }//GEN-LAST:event_btnRefreshProviderActionPerformed

    private void btnRefreshClientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshClientsMouseEntered
        jTabbedPane1.setEnabled(true);
    }//GEN-LAST:event_btnRefreshClientsMouseEntered

    private void btnRefreshClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshClientsMouseExited
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_btnRefreshClientsMouseExited

    private void btnRefreshProviderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshProviderMouseEntered
        jTabbedPane1.setEnabled(true);
    }//GEN-LAST:event_btnRefreshProviderMouseEntered

    private void btnRefreshProviderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshProviderMouseExited
        jTabbedPane1.setEnabled(false);
    }//GEN-LAST:event_btnRefreshProviderMouseExited

    private void btnProvidersPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProvidersPaidActionPerformed
        if(Name.equals(""))
        {
            JOptionPane.showMessageDialog(null, "الرجاء تحديد المزود");
        }
        else
        {
            //String name = tblProviders.getValueAt(r, 3).toString();
            String debt = tblProviders.getValueAt(r, 2).toString();
            new ProviderPaid(Name,debt).setVisible(true);
            Name = "";
        }
    }//GEN-LAST:event_btnProvidersPaidActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        tblClients.clearSelection();
        jPanel2.requestFocus();
        Name = "";
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        tblProviders.clearSelection();
        jPanel3.requestFocus();
        Name = "";
    }//GEN-LAST:event_jPanel3MouseClicked

    private void cmbClientsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClientsItemStateChanged
        
        String currency = cmbClients.getSelectedItem().toString();
        
        if(currency.equals("د.ع"))
        {
            fillTable("SELECT Address, Phone, CONCAT(FORMAT(Debt, 0), ' د.ع') AS 'Debt', Name FROM client WHERE Currency = 'د.ع'", tblClients); 
        }
        else
        {
             fillTable("SELECT Address, Phone, CONCAT('$ ', FORMAT(Debt, 0)) AS 'Debt', Name FROM client WHERE Currency = '$'", tblClients); 
        }
       
        
    }//GEN-LAST:event_cmbClientsItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientsAndProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientsAndProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientsAndProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsAndProvider.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientsAndProvider().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnClientsPaid;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDelete1;
    private javax.swing.JButton btnProvider;
    private javax.swing.JButton btnProvidersPaid;
    private javax.swing.JButton btnRefreshClients;
    private javax.swing.JButton btnRefreshProvider;
    private javax.swing.JComboBox<String> cmbClients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable tblClients;
    private javax.swing.JTable tblProviders;
    private javax.swing.JTextField txtSearchClients;
    private javax.swing.JTextField txtSearchProviders;
    // End of variables declaration//GEN-END:variables
}
