/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sql.go;

/**
 *
 * @author Mohammad
 */
public class ClientsPaid extends javax.swing.JFrame {
    
    go g = new go();
    //boolean flag = false;
    private String id;
    private int returnPrice;
    
    
    public ClientsPaid() {
        initComponents();         
    }
    
    public ClientsPaid(String name, String d)
    {
        initComponents();
        
        
        //this.Name = name;
        txtName.setText(name);
        String debt = d.replace(",", "").replace(" د.ع", "").replace("$ ", "");
        if(!debt.equals(""))
        { 
            float quan = Float.parseFloat(debt);
            String comma = String.format ("%,.0f", quan);
            txtDebt.setText(comma);   
        }
        
    }
    
    public ClientsPaid(String name, String id,int sellDebt, int returnPrice, String lblName)
    {
        initComponents();
        
        //this.Name = name;
        this.id = id;
        this.returnPrice = returnPrice;
        jLabel4.setText(lblName);
        txtName.setText(name);
        
        float quan = (float) sellDebt;
        String comma = String.format ("%,.0f", quan);
        txtDebt.setText(comma);   
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAddEditItem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        btnAdd1 = new javax.swing.JButton();
        txtDebt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(14, 114, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEditItem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddEditItem.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEditItem.setText("دفع ديون الزبون");
        jPanel2.add(lblAddEditItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("اسم الزبون:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 110, 30));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtName.setMargin(new java.awt.Insets(2, 2, 2, 5));
        jPanel3.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 220, 30));

        btnAdd1.setBackground(new java.awt.Color(235, 235, 235));
        btnAdd1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(14, 114, 61));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/commission.png"))); // NOI18N
        btnAdd1.setText("دفع");
        btnAdd1.setBorderPainted(false);
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.setFocusable(false);
        btnAdd1.setIconTextGap(10);
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 180, 40));

        txtDebt.setEditable(false);
        txtDebt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDebt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDebt.setMargin(new java.awt.Insets(2, 2, 2, 5));
        jPanel3.add(txtDebt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 220, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ديون الزبون:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 130, 30));

        txtPaid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPaid.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtPaid.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtPaid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPaidFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPaidFocusLost(evt);
            }
        });
        txtPaid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPaidKeyReleased(evt);
            }
        });
        jPanel3.add(txtPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 220, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("المبلغ المدفوع:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 110, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 330));

        setSize(new java.awt.Dimension(430, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
   
        if(txtPaid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "الرجاء ملئ حقل المبلغ");
        }
        else
        {
            String CName = txtName.getText();
            DateFormat dateFormat = new SimpleDateFormat("YYYY-MM-dd"); //display your format.
            Date d = new Date();
            String datePaid = dateFormat.format(d);
            
            int paid = Integer.parseInt(txtPaid.getText().replace(",", ""));
            int debt = Integer.parseInt(txtDebt.getText().replace(",", ""));
            
            
//            if(jLabel4.getText().equals("ديون عملية البيع :"))
//            {
//                debt = returnPrice;
//            }
            
            if(paid <= debt)
            {
                if(jLabel4.getText().equals("ديون عملية البيع :"))
                {
                    String sql = "UPDATE export SET Debt = Debt -'"+ paid +"' WHERE ID = '"+ id +"'";
                    g.query(sql);
                }

                String sql = "UPDATE client SET Debt = Debt -'" + paid + "' WHERE Name ='" + CName +"'";
                g.query(sql);

                String sql1 = "SELECT ID,Currency FROM client where Name = '" + CName + "'";
                String clientInfo[] = go.GetInformation(sql1,2);
                String CID = clientInfo[0];
                String currency = clientInfo[1];
                
                String sql2 = "INSERT INTO debthistorypaid (ClientID,TotalDebt,DebtPaid,DatePaid,Currency) VALUES ('"+CID+"','"+debt+"','"+paid+"','"+datePaid+"','"+currency+"')";
                g.query(sql2);
                
                JOptionPane.showMessageDialog(null, "تم الدفع");
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "المبلغ المدفوع غير صحيح");
            }
        }
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jPanel3.requestFocus();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void txtPaidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidFocusLost
        
        String Paid = txtPaid.getText().replace(",", "");
        if(!Paid.equals(""))
        {
            float quan = Float.parseFloat(Paid);
            String comma = String.format ("%,.0f", quan);
            txtPaid.setText(comma);
        }
    }//GEN-LAST:event_txtPaidFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtPaid.requestFocus();
    }//GEN-LAST:event_formWindowOpened

    private void txtPaidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPaidKeyReleased
        String text = txtPaid.getText();
        if(!text.equals(""))
        {
            if(!Character.isDigit(text.charAt(text.length()-1)))
            {
                txtPaid.setText(""+text.substring(0, text.length()- 1));
                return;
            }
            if(!Character.isDigit(text.charAt(0)))
            {
                txtPaid.setText(""+text.substring(1));
            }
        }
    }//GEN-LAST:event_txtPaidKeyReleased

    private void txtPaidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPaidFocusGained
        String Paid = txtPaid.getText().replace(",", "");
    }//GEN-LAST:event_txtPaidFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientsPaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientsPaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientsPaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientsPaid.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientsPaid().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblAddEditItem;
    private javax.swing.JTextField txtDebt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPaid;
    // End of variables declaration//GEN-END:variables
}
