/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

//import java.awt.Frame;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import sql.go;

//import javax.swing.JFrame;

/**
 *
 * @author Mohsin
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    go g = new go();
    public MainForm() {
        initComponents();
        
        lblSign.setVisible(false);
        String sql1 = "SELECT Quantity FROM `material` WHERE Quantity < 5";
        String result = g.getData(sql1);
        
        if(!result.equals(""))
        {
            lblSign.setVisible(true);
        }
        /*Toolkit kit = Toolkit.getDefaultToolkit();
        
        int w = (int)kit.getScreenSize().getWidth();
        int h = (int)kit.getScreenSize().getHeight();
        
        System.out.println(w + " " + h);
        setSize(w,h);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlWarehouse = new javax.swing.JPanel();
        lblWarehouseIcon = new javax.swing.JLabel();
        lblWarehouse = new javax.swing.JLabel();
        pnlSell = new javax.swing.JPanel();
        lblSellIcon = new javax.swing.JLabel();
        lblSell = new javax.swing.JLabel();
        pnlBuy = new javax.swing.JPanel();
        lblBuyIcon = new javax.swing.JLabel();
        lblBuy = new javax.swing.JLabel();
        pnlProvider = new javax.swing.JPanel();
        lblProviderIcon = new javax.swing.JLabel();
        lblProviderAndClient = new javax.swing.JLabel();
        pnlReport = new javax.swing.JPanel();
        lblReportIcon = new javax.swing.JLabel();
        lblReport = new javax.swing.JLabel();
        pnlSetting = new javax.swing.JPanel();
        lblReport1 = new javax.swing.JLabel();
        lblSign = new javax.swing.JLabel();
        pnlReturn = new javax.swing.JPanel();
        lblReturn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(14, 114, 61));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("برنامج ادارة المبيعات");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(263, 263, 263))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlWarehouse.setBackground(new java.awt.Color(230, 230, 250));
        pnlWarehouse.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlWarehouseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlWarehouseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlWarehouseMouseExited(evt);
            }
        });

        lblWarehouseIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarehouseIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/warehouse1.png"))); // NOI18N
        lblWarehouseIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWarehouseIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblWarehouseIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblWarehouseIconMouseExited(evt);
            }
        });

        lblWarehouse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWarehouse.setForeground(new java.awt.Color(14, 114, 61));
        lblWarehouse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarehouse.setText("المخزن");
        lblWarehouse.setToolTipText("");
        lblWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWarehouseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlWarehouseLayout = new javax.swing.GroupLayout(pnlWarehouse);
        pnlWarehouse.setLayout(pnlWarehouseLayout);
        pnlWarehouseLayout.setHorizontalGroup(
            pnlWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWarehouseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWarehouse, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lblWarehouseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlWarehouseLayout.setVerticalGroup(
            pnlWarehouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWarehouseLayout.createSequentialGroup()
                .addComponent(lblWarehouse, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblWarehouseIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(pnlWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 130, 120));

        pnlSell.setBackground(new java.awt.Color(230, 230, 250));
        pnlSell.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSellMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSellMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSellMouseExited(evt);
            }
        });

        lblSellIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSellIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/shopping-cart3.png"))); // NOI18N
        lblSellIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSellIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSellIconMouseExited(evt);
            }
        });

        lblSell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSell.setForeground(new java.awt.Color(14, 114, 61));
        lblSell.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSell.setText("البيع");
        lblSell.setToolTipText("");
        lblSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSellMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlSellLayout = new javax.swing.GroupLayout(pnlSell);
        pnlSell.setLayout(pnlSellLayout);
        pnlSellLayout.setHorizontalGroup(
            pnlSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSellLayout.createSequentialGroup()
                .addComponent(lblSellIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(lblSell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        pnlSellLayout.setVerticalGroup(
            pnlSellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSellLayout.createSequentialGroup()
                .addComponent(lblSell, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSellIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(pnlSell, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 60, 130, 120));

        pnlBuy.setBackground(new java.awt.Color(230, 230, 250));
        pnlBuy.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlBuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBuyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBuyMouseExited(evt);
            }
        });

        lblBuyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/order1.png"))); // NOI18N
        lblBuyIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBuyIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuyIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBuyIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBuyIconMouseExited(evt);
            }
        });

        lblBuy.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBuy.setForeground(new java.awt.Color(14, 114, 61));
        lblBuy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuy.setText("الشراء");
        lblBuy.setToolTipText("");
        lblBuy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBuyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlBuyLayout = new javax.swing.GroupLayout(pnlBuy);
        pnlBuy.setLayout(pnlBuyLayout);
        pnlBuyLayout.setHorizontalGroup(
            pnlBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBuyIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(lblBuy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );
        pnlBuyLayout.setVerticalGroup(
            pnlBuyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBuyLayout.createSequentialGroup()
                .addComponent(lblBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(pnlBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 130, 120));

        pnlProvider.setBackground(new java.awt.Color(230, 230, 250));
        pnlProvider.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlProvider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlProvider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlProviderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlProviderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlProviderMouseExited(evt);
            }
        });

        lblProviderIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProviderIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delivery-man.png"))); // NOI18N
        lblProviderIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProviderIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProviderIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProviderIconMouseExited(evt);
            }
        });

        lblProviderAndClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProviderAndClient.setForeground(new java.awt.Color(14, 114, 61));
        lblProviderAndClient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProviderAndClient.setText("الزبائن والمزودين");
        lblProviderAndClient.setToolTipText("");
        lblProviderAndClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProviderAndClientMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlProviderLayout = new javax.swing.GroupLayout(pnlProvider);
        pnlProvider.setLayout(pnlProviderLayout);
        pnlProviderLayout.setHorizontalGroup(
            pnlProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProviderLayout.createSequentialGroup()
                .addGroup(pnlProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProviderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblProviderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 111, Short.MAX_VALUE))
                    .addComponent(lblProviderAndClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlProviderLayout.setVerticalGroup(
            pnlProviderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProviderLayout.createSequentialGroup()
                .addComponent(lblProviderAndClient, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProviderIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(pnlProvider, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 130, 120));

        pnlReport.setBackground(new java.awt.Color(230, 230, 250));
        pnlReport.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReportMouseExited(evt);
            }
        });

        lblReportIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/checklist.png"))); // NOI18N
        lblReportIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportIconMouseExited(evt);
            }
        });

        lblReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReport.setForeground(new java.awt.Color(14, 114, 61));
        lblReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport.setText("التقارير");
        lblReport.setToolTipText("");
        lblReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnlReportLayout.createSequentialGroup()
                        .addComponent(lblReport, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReportLayout.createSequentialGroup()
                .addComponent(lblReport, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblReportIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel2.add(pnlReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 240, 140, 120));

        pnlSetting.setBackground(new java.awt.Color(230, 230, 250));
        pnlSetting.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlSettingMouseExited(evt);
            }
        });

        lblReport1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReport1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/settings3.png"))); // NOI18N
        lblReport1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReport1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReport1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReport1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlSettingLayout = new javax.swing.GroupLayout(pnlSetting);
        pnlSetting.setLayout(pnlSettingLayout);
        pnlSettingLayout.setHorizontalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addComponent(lblReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSettingLayout.setVerticalGroup(
            pnlSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSettingLayout.createSequentialGroup()
                .addComponent(lblReport1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(pnlSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 370, 60, 50));

        lblSign.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblSign.setForeground(new java.awt.Color(255, 0, 0));
        lblSign.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSign.setText("!");
        jPanel2.add(lblSign, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 30, 40));

        pnlReturn.setBackground(new java.awt.Color(230, 230, 250));
        pnlReturn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlReturnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlReturnMouseExited(evt);
            }
        });

        lblReturn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(14, 114, 61));
        lblReturn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReturn.setText("استرجاع");
        lblReturn.setToolTipText("");
        lblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnMouseClicked(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bag5.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlReturnLayout = new javax.swing.GroupLayout(pnlReturn);
        pnlReturn.setLayout(pnlReturnLayout);
        pnlReturnLayout.setHorizontalGroup(
            pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReturn, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlReturnLayout.setVerticalGroup(
            pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnLayout.createSequentialGroup()
                .addComponent(lblReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(pnlReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 130, 120));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(720, 546));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlWarehouseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWarehouseMouseEntered
        pnlWarehouse.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlWarehouseMouseEntered

    private void pnlWarehouseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWarehouseMouseExited
        pnlWarehouse.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlWarehouseMouseExited

    private void pnlSellMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSellMouseEntered
        pnlSell.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlSellMouseEntered

    private void pnlSellMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSellMouseExited
        pnlSell.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlSellMouseExited

    private void pnlBuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBuyMouseEntered
        pnlBuy.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlBuyMouseEntered

    private void pnlBuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBuyMouseExited
        pnlBuy.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlBuyMouseExited

    private void pnlReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportMouseEntered
        pnlReport.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlReportMouseEntered

    private void pnlReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportMouseExited
        pnlReport.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlReportMouseExited

    private void pnlWarehouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlWarehouseMouseClicked
        this.dispose();
        
        new Warehouse().setVisible(true);
    }//GEN-LAST:event_pnlWarehouseMouseClicked

    private void pnlProviderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProviderMouseEntered
        pnlProvider.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlProviderMouseEntered

    private void pnlProviderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProviderMouseExited
        pnlProvider.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlProviderMouseExited

    private void pnlSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSellMouseClicked
        this.dispose();
        
        new Sale().setVisible(true);
    }//GEN-LAST:event_pnlSellMouseClicked

    private void pnlProviderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlProviderMouseClicked
        this.dispose();
        
        new ClientsAndProvider().setVisible(true);
    }//GEN-LAST:event_pnlProviderMouseClicked

    private void pnlBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBuyMouseClicked
        this.dispose();
        
        new Buy().setVisible(true);
    }//GEN-LAST:event_pnlBuyMouseClicked

    private void pnlReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReportMouseClicked
        this.dispose();
        
        new reports().setVisible(true);
    }//GEN-LAST:event_pnlReportMouseClicked

    private void lblBuyIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuyIconMouseClicked
        this.dispose();
        
        new Buy().setVisible(true);
    }//GEN-LAST:event_lblBuyIconMouseClicked

    private void lblSellIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellIconMouseClicked
        this.dispose();
        
        new Sale().setVisible(true);
    }//GEN-LAST:event_lblSellIconMouseClicked

    private void lblWarehouseIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWarehouseIconMouseClicked
        this.dispose();
        
        new Warehouse().setVisible(true);
    }//GEN-LAST:event_lblWarehouseIconMouseClicked

    private void lblProviderIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProviderIconMouseClicked
        this.dispose();
        
        new ClientsAndProvider().setVisible(true);
    }//GEN-LAST:event_lblProviderIconMouseClicked

    private void lblReportIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportIconMouseClicked
        this.dispose();
        
        new reports().setVisible(true);
    }//GEN-LAST:event_lblReportIconMouseClicked

    private void lblBuyIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuyIconMouseEntered
        pnlBuy.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_lblBuyIconMouseEntered

    private void lblBuyIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuyIconMouseExited
        pnlBuy.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblBuyIconMouseExited

    private void lblSellIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellIconMouseEntered
        pnlSell.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_lblSellIconMouseEntered

    private void lblSellIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellIconMouseExited
        pnlSell.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblSellIconMouseExited

    private void lblWarehouseIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWarehouseIconMouseEntered
        pnlWarehouse.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_lblWarehouseIconMouseEntered

    private void lblWarehouseIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWarehouseIconMouseExited
        pnlWarehouse.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblWarehouseIconMouseExited

    private void lblProviderIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProviderIconMouseEntered
        pnlProvider.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_lblProviderIconMouseEntered

    private void lblProviderIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProviderIconMouseExited
        pnlProvider.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblProviderIconMouseExited

    private void lblReportIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportIconMouseEntered
        pnlReport.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_lblReportIconMouseEntered

    private void lblReportIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportIconMouseExited
        pnlReport.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblReportIconMouseExited

    private void lblReport1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReport1MouseClicked
        new Setting().setVisible(true);
    }//GEN-LAST:event_lblReport1MouseClicked

    private void lblReport1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReport1MouseEntered
        pnlSetting.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_lblReport1MouseEntered

    private void lblReport1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReport1MouseExited
        pnlSetting.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_lblReport1MouseExited

    private void pnlSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSettingMouseClicked
        new Setting().setVisible(true);
    }//GEN-LAST:event_pnlSettingMouseClicked

    private void pnlSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSettingMouseEntered
        pnlSetting.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlSettingMouseEntered

    private void pnlSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSettingMouseExited
        pnlSetting.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlSettingMouseExited

    private void pnlReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseClicked
        this.dispose();
        
        new Return().setVisible(true);
    }//GEN-LAST:event_pnlReturnMouseClicked

    private void pnlReturnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseEntered
        pnlReturn.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_pnlReturnMouseEntered

    private void pnlReturnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnMouseExited
        pnlReturn.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_pnlReturnMouseExited

    private void lblWarehouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWarehouseMouseClicked
        this.dispose();
        
        new Warehouse().setVisible(true);
    }//GEN-LAST:event_lblWarehouseMouseClicked

    private void lblSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSellMouseClicked
        this.dispose();
        
        new Sale().setVisible(true);
    }//GEN-LAST:event_lblSellMouseClicked

    private void lblBuyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuyMouseClicked
        this.dispose();
        
        new Buy().setVisible(true);
    }//GEN-LAST:event_lblBuyMouseClicked

    private void lblProviderAndClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProviderAndClientMouseClicked
        this.dispose();
        
        new ClientsAndProvider().setVisible(true);
    }//GEN-LAST:event_lblProviderAndClientMouseClicked

    private void lblReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportMouseClicked
        this.dispose();
        
        new reports().setVisible(true);
    }//GEN-LAST:event_lblReportMouseClicked

    private void lblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseClicked
        this.dispose();
        
        new Return().setVisible(true);
    }//GEN-LAST:event_lblReturnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.dispose();
        
        new Return().setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        pnlReturn.setBackground(new Color(207,207,225));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        pnlReturn.setBackground(new Color(230,230,250));
    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblBuy;
    private javax.swing.JLabel lblBuyIcon;
    private javax.swing.JLabel lblProviderAndClient;
    private javax.swing.JLabel lblProviderIcon;
    private javax.swing.JLabel lblReport;
    private javax.swing.JLabel lblReport1;
    private javax.swing.JLabel lblReportIcon;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblSell;
    private javax.swing.JLabel lblSellIcon;
    private javax.swing.JLabel lblSign;
    private javax.swing.JLabel lblWarehouse;
    private javax.swing.JLabel lblWarehouseIcon;
    private javax.swing.JPanel pnlBuy;
    private javax.swing.JPanel pnlProvider;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JPanel pnlSell;
    private javax.swing.JPanel pnlSetting;
    private javax.swing.JPanel pnlWarehouse;
    // End of variables declaration//GEN-END:variables
}
