/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.JTextComponent;
import sql.go;

/**
 *
 * @author Mohammad
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form AddClinte
     */
    String path = "";
    go g = new go();
    public Setting() {
        initComponents();
        
        lblImage.setVisible(false);
        btnImage.setVisible(false);
        btnAdd1.setVisible(false);
        jLabel12.setVisible(false);
        cmbWarehouseName.setVisible(false);
        btnEdit.setVisible(false);
        
        fillComboBoxGrop();
        
        String sql1 = "SELECT Percent,dollar FROM setting LIMIT 1";
        String[] settng = go.GetInformation(sql1, 2);
        String percent = settng[0];
        String dollar = settng[1]; 

        cmbPercent.setSelectedItem(percent.concat(" %"));
        txtDollar.setText(dollar.replace(".0", ""));
    }

    public void fillComboBoxGrop()
    {
        cmbGrop.removeAllItems();
        String sql1 = "SELECT * FROM grop";
        g.fillCombo(cmbGrop,sql1);
        cmbGrop.setSelectedIndex(-1);
        
        String sql2 = "SELECT * FROM warehouse";
        g.fillCombo(cmbWarehouseName,sql2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblAddEditItem = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        cmbPercent = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmbGrop = new javax.swing.JComboBox<>();
        btnAdd2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtDollar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAdd3 = new javax.swing.JButton();
        cmbWarehouseName = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(14, 114, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEditItem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAddEditItem.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEditItem.setText("الاعدادات");
        jPanel2.add(lblAddEditItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 35));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("النوع");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 90, 40));

        btnAdd1.setBackground(new java.awt.Color(235, 235, 235));
        btnAdd1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(14, 114, 61));
        btnAdd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnAdd1.setText("حفظ");
        btnAdd1.setBorderPainted(false);
        btnAdd1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd1.setEnabled(false);
        btnAdd1.setFocusable(false);
        btnAdd1.setIconTextGap(8);
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 40));

        cmbPercent.setBackground(new java.awt.Color(254, 255, 255));
        cmbPercent.setEditable(true);
        cmbPercent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbPercent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 %", "0.5 %", "1 %", "1.5 %", "2 %", "2.5 %", "3 %", "3.5 %", "4 %", "4.5 %", "5 %", "5.5 %", "6 %", "6.5 %", "7 %", "7.5 %", "8 %", "8.5 %", "9 %", "9.5 %", "10 %" }));
        cmbPercent.setBorder(null);
        cmbPercent.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbPercent.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPercentItemStateChanged(evt);
            }
        });
        jPanel3.add(cmbPercent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 150, 40));

        btnEdit.setBackground(new java.awt.Color(235, 235, 235));
        btnEdit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(14, 114, 61));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete-list.png"))); // NOI18N
        btnEdit.setText("تفريغ");
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setEnabled(false);
        btnEdit.setFocusable(false);
        btnEdit.setIconTextGap(8);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("نسبة الارباح");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 90, 40));

        lblImage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setText("اختر صورة");
        lblImage.setEnabled(false);
        jPanel3.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 80, 40));

        btnImage.setBackground(new java.awt.Color(255, 255, 255));
        btnImage.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btnImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/photo-camera.png"))); // NOI18N
        btnImage.setText("Image");
        btnImage.setBorderPainted(false);
        btnImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImage.setEnabled(false);
        btnImage.setFocusable(false);
        btnImage.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnImage.setIconTextGap(10);
        btnImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnImageMouseExited(evt);
            }
        });
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });
        jPanel3.add(btnImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 150, 40));

        btnDelete.setBackground(new java.awt.Color(235, 235, 235));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(14, 114, 61));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/garbage.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.setIconTextGap(8);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 40));

        cmbGrop.setBackground(new java.awt.Color(254, 255, 255));
        jPanel3.add(cmbGrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 38));

        btnAdd2.setBackground(new java.awt.Color(235, 235, 235));
        btnAdd2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(14, 114, 61));
        btnAdd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnAdd2.setText("حفظ");
        btnAdd2.setBorderPainted(false);
        btnAdd2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd2.setFocusable(false);
        btnAdd2.setIconTextGap(8);
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("تفريغ المخزن");
        jLabel12.setEnabled(false);
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 90, 40));

        txtDollar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDollar.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDollar.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtDollar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDollarKeyReleased(evt);
            }
        });
        jPanel3.add(txtDollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 150, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("سعر الصرف");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 90, 40));

        btnAdd3.setBackground(new java.awt.Color(235, 235, 235));
        btnAdd3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnAdd3.setForeground(new java.awt.Color(14, 114, 61));
        btnAdd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        btnAdd3.setText("حفظ");
        btnAdd3.setBorderPainted(false);
        btnAdd3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd3.setFocusable(false);
        btnAdd3.setIconTextGap(8);
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 40));

        cmbWarehouseName.setBackground(new java.awt.Color(254, 255, 255));
        cmbWarehouseName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbWarehouseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "جميع المخازن" }));
        cmbWarehouseName.setEnabled(false);
        jPanel3.add(cmbWarehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 150, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 430, 330));

        setSize(new java.awt.Dimension(430, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed

        //String percent = cmbPercent.getSelectedItem().toString().replace("%", "");
        //String percent = ((JTextComponent)cmbPercent.getEditor().getEditorComponent()).getText().replace("%", "");
//        String sql5 = "";
//        System.out.println(percent);
//        if(path.equals(""))
//        {
//            int dialogResult = JOptionPane.showConfirmDialog(null, "لم يتم تحديد الصورة هل تريد الحفظ", "انتبه", JOptionPane.YES_NO_OPTION);
//            if(dialogResult == 0)
//            {
//                sql5 = "UPDATE setting SET Percent = ? ,Image = ?";
//                g.setting(sql5 ,percent, "");
//            }
//        }
//        else
//        {
//            sql5 = "UPDATE setting SET Percent = ? ,Image = ?";
//            g.setting(sql5 ,percent, path);
//        }
        
//        String sql5 = "UPDATE setting SET Percent = ? ,Image = ?";
//        g.setting(sql5 ,percent, "");
//        
//        JOptionPane.showMessageDialog(null, "تم الحفظ");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void btnImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageMouseEntered
        btnImage.setBackground(Color.decode("#E0DDDD"));
    }//GEN-LAST:event_btnImageMouseEntered

    private void btnImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageMouseExited
        btnImage.setBackground(Color.decode("#FAFAFA"));
    }//GEN-LAST:event_btnImageMouseExited

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed

        JFileChooser fc=new JFileChooser();
        FileNameExtensionFilter filter=new FileNameExtensionFilter("* IMAGE", "jpg","png","gif");
        fc.addChoosableFileFilter(filter);
        if (fc.showSaveDialog(null)== JFileChooser.APPROVE_OPTION) 
        {
            File selectedFile=fc.getSelectedFile();
            path=selectedFile.getAbsolutePath();
            System.out.println("done");
        }
    }//GEN-LAST:event_btnImageActionPerformed

    private void cmbPercentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPercentItemStateChanged
//        String percent = ((JTextComponent)cmbPercent.getEditor().getEditorComponent()).getText().replace("%", "");
//        String sql5 = "UPDATE setting SET Percent = ? ,Image = ?";
//        g.setting(sql5 ,percent, "");
    }//GEN-LAST:event_cmbPercentItemStateChanged

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(cmbWarehouseName.getSelectedIndex() == 0)
        {
            int dialogResult = JOptionPane.showConfirmDialog(null, "سوف يتم تفريغ المخزن", "انتبه", JOptionPane.YES_NO_OPTION);
            if(dialogResult == 0)
            {
                String sql = "TRUNCATE material";
                String result = g.query(sql);
                JOptionPane.showMessageDialog(null, "تم التفريغ");
            }
        }
        else
        {
            String warehouseName = cmbWarehouseName.getSelectedItem().toString();
            int dialogResult = JOptionPane.showConfirmDialog(null, "سوف يتم تفريغ المخزن", "انتبه", JOptionPane.YES_NO_OPTION);
            if(dialogResult == 0)
            {
//                String sql = "DELETE FROM material WHERE WarehouseName ='"+ warehouseName +"'";
                String sql = "UPDATE material SET Quantity=0 WHERE WarehouseName='"+ warehouseName +"'";
                String result = g.query(sql);
                JOptionPane.showMessageDialog(null, "تم التفريغ");
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int selectedIndex = cmbGrop.getSelectedIndex();
        if(selectedIndex == -1)
        {
            JOptionPane.showMessageDialog(null, "الرجاء اختيار العنصر المراد حذفه");
        }
        else
        {
            Object name = cmbGrop.getSelectedItem();
            int dialogResult = JOptionPane.showConfirmDialog(null, "هن انت متأكد من حذف هذا العنصر", "انتبه", JOptionPane.YES_NO_OPTION);
            if(dialogResult == 0)
            {
                String sql = "DELETE FROM grop WHERE Name ='" + name + "'";
                String result = g.query(sql);

                JOptionPane.showMessageDialog(null, "تم الحذف");

                cmbGrop.removeItemAt(selectedIndex);
                cmbGrop.setSelectedIndex(-1);
            }
            else
            {
               cmbGrop.setSelectedIndex(-1);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        jPanel3.requestFocus();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
        String percent = ((JTextComponent)cmbPercent.getEditor().getEditorComponent()).getText().replace("%", "").trim();
//        String sql5 = "UPDATE setting SET Percent =? ,Image =?";
//        String result = g.setting(sql5 ,percent, "");
        String sql5 = "UPDATE setting SET Percent ='"+ percent +"' , Image = null, dollar = dollar";
        String result = g.query(sql5);
        if(result.equals(""))
        {
            JOptionPane.showMessageDialog(null, "تم الحفظ");
        }
        else
        {
            JOptionPane.showMessageDialog(null , "Error: " + result);
        }
        
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void txtDollarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDollarKeyReleased
        if(!txtDollar.getText().equals(""))
        {
            if(!Character.isDigit(txtDollar.getText().charAt(txtDollar.getText().length()-1)))
            {
                txtDollar.setText(""+txtDollar.getText().substring(0, txtDollar.getText().length()- 1));
                return;
            }
            if(!Character.isDigit(txtDollar.getText().charAt(0)))
            {
                txtDollar.setText(""+txtDollar.getText().substring(1));
            }
        }
    }//GEN-LAST:event_txtDollarKeyReleased

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
        String dollar = txtDollar.getText();
        String sql5 = "UPDATE setting SET Percent = Percent , Image = null, dollar = '" +dollar+"'";
        String result = g.query(sql5);
        if(result.equals(""))
        {
            JOptionPane.showMessageDialog(null, "تم الحفظ");
        }
        else
        {
            JOptionPane.showMessageDialog(null , "Error: " + result);
        }
    }//GEN-LAST:event_btnAdd3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnImage;
    private javax.swing.JComboBox<String> cmbGrop;
    public javax.swing.JComboBox<String> cmbPercent;
    private javax.swing.JComboBox<String> cmbWarehouseName;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblAddEditItem;
    private javax.swing.JLabel lblImage;
    private javax.swing.JTextField txtDollar;
    // End of variables declaration//GEN-END:variables
}
