/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.JTextComponent;
import sql.go;


/**
 *
 * @author Mohammad
 */
public class Warehouse extends javax.swing.JFrame {

    //ArrayList warehouse = new ArrayList();
    go g = new go();
    String ID = "";
    int r = -1;
    public Warehouse() {
        initComponents();
        
        
        tblWarehouse.getTableHeader().setReorderingAllowed(false);
        
        JTableHeader header = tblWarehouse.getTableHeader();
        header.setForeground(new Color(14,114,61));
        header.setFont(new Font("Tahoma" , Font.BOLD , 16));
        
        setCellsAlignment(tblWarehouse, SwingConstants.CENTER);
        fillTable();
        tblWarehouse.setDefaultEditor(Object.class, null);
        fillCombobox();
        //cmbWarehouse.setFocusable(false);
        
        btnDelete.setVisible(false);
        
    }

    private  void setCellsAlignment(JTable table, int alignment)
    {
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(alignment);

        TableModel tableModel = table.getModel();

        for (int columnIndex = 0; columnIndex < tableModel.getColumnCount(); columnIndex++)
        {
            table.getColumnModel().getColumn(columnIndex).setCellRenderer(rightRenderer);
        }
    }
    
    private void fillTable()
    {
        String sql1 = "SELECT WarehouseName,CONCAT('$ ', FORMAT(Price,0)),Type,Quantity,Name,ID FROM material";
        g.fillToJTable(sql1, tblWarehouse);
    }
    
    void filter(String query)
    {
        DefaultTableModel model= (DefaultTableModel) tblWarehouse.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        tblWarehouse.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    void fillCombobox()
    {
        String sql = "SELECT * FROM warehouse";
        g.fillCombo(cmbWarehouseName,sql);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWarehouse = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnEditInfo = new javax.swing.JButton();
        btnRefreshClients = new javax.swing.JButton();
        cmbWarehouse = new javax.swing.JComboBox<>();
        cmbWarehouseName = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(14, 114, 61));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("المخزن");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 120, 30));

        btnBack.setBackground(new java.awt.Color(235, 235, 235));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack.setForeground(new java.awt.Color(14, 114, 61));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/back.png"))); // NOI18N
        btnBack.setText("الرجوع");
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setFocusable(false);
        btnBack.setIconTextGap(8);
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 50));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new java.awt.Color(235, 235, 235));
        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(14, 114, 61));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/garbage.png"))); // NOI18N
        btnDelete.setText("حذف");
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.setFocusable(false);
        btnDelete.setIconTextGap(8);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 500, 170, 50));

        tblWarehouse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblWarehouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "المخزن", "السعر", "النوع", "الكمية", "اسم المادة", "الرقم"
            }
        ));
        tblWarehouse.setFocusable(false);
        tblWarehouse.setRowHeight(26);
        tblWarehouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWarehouseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWarehouse);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 990, 420));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifying-glass.png"))); // NOI18N
        jLabel4.setText("البحث");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, 40));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtSearch.setMargin(new java.awt.Insets(2, 2, 2, 5));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel5.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 220, 40));

        btnEditInfo.setBackground(new java.awt.Color(235, 235, 235));
        btnEditInfo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEditInfo.setForeground(new java.awt.Color(14, 114, 61));
        btnEditInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pencil.png"))); // NOI18N
        btnEditInfo.setText("تعديل ");
        btnEditInfo.setBorderPainted(false);
        btnEditInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEditInfo.setFocusable(false);
        btnEditInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditInfoActionPerformed(evt);
            }
        });
        jPanel5.add(btnEditInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 170, 50));

        btnRefreshClients.setBackground(new java.awt.Color(235, 235, 235));
        btnRefreshClients.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRefreshClients.setForeground(new java.awt.Color(14, 114, 61));
        btnRefreshClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        btnRefreshClients.setText("تحديث");
        btnRefreshClients.setBorderPainted(false);
        btnRefreshClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefreshClients.setFocusable(false);
        btnRefreshClients.setIconTextGap(8);
        btnRefreshClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshClientsActionPerformed(evt);
            }
        });
        jPanel5.add(btnRefreshClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 120, 40));

        cmbWarehouse.setBackground(new java.awt.Color(254, 255, 255));
        cmbWarehouse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbWarehouse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "جميع السلع", "سلع على وشك النفاذ", "سلع نفذت" }));
        cmbWarehouse.setBorder(null);
        cmbWarehouse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbWarehouse.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWarehouseItemStateChanged(evt);
            }
        });
        jPanel5.add(cmbWarehouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 210, 40));

        cmbWarehouseName.setBackground(new java.awt.Color(254, 255, 255));
        cmbWarehouseName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbWarehouseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "جميع المخازن" }));
        cmbWarehouseName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWarehouseNameItemStateChanged(evt);
            }
        });
        cmbWarehouseName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbWarehouseNameFocusGained(evt);
            }
        });
        jPanel5.add(cmbWarehouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("المخزن");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 50, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1020, 570));

        setSize(new java.awt.Dimension(1024, 648));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setBackground(new Color(225,225,225));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setBackground(new Color(245,245,245));
    }//GEN-LAST:event_btnBackMouseExited

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
        
        new MainForm().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
       if(ID.equals(""))
       {
           JOptionPane.showMessageDialog(null, "الرجاء تحديد العنصر المراد حذفه");
       }
       else
       {
            int dialogResult = JOptionPane.showConfirmDialog(null, "هن انت متأكد من حذف هذا العنصر", "انتبه", JOptionPane.YES_NO_OPTION);
            if(dialogResult == 0)
            {
                System.out.println(ID);
                String sql = "DELETE FROM material WHERE ID ='" + ID + "'";
                String result = g.query(sql);
                System.out.println(result);

                DefaultTableModel model=(DefaultTableModel)tblWarehouse.getModel();
                model.removeRow(r);
                tblWarehouse.setModel(model);

                JOptionPane.showMessageDialog(null, "تم الحذف");
                
                tblWarehouse.clearSelection();
                ID = "";
            }
            else
            {
                tblWarehouse.clearSelection();
                ID = "";
            }   
       }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
        String query = txtSearch.getText();
        filter(query);
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void tblWarehouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWarehouseMouseClicked
        
        if(tblWarehouse.getSelectedRow() != -1)
        {
            r = tblWarehouse.getSelectedRow();
            ID = tblWarehouse.getValueAt(r, 5).toString();
        }
        else
        {
            ID = "";
        }
    }//GEN-LAST:event_tblWarehouseMouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        jPanel5.requestFocus();
        tblWarehouse.clearSelection();
        ID = "";
    }//GEN-LAST:event_jPanel5MouseClicked

    private void btnEditInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditInfoActionPerformed
        if(ID.equals(""))
        {
            JOptionPane.showMessageDialog(null, "الرجاء تحديد المادة");
        }
        else
        {
            String id = tblWarehouse.getValueAt(r, 5).toString();
            String name = tblWarehouse.getValueAt(r, 4).toString();
            String type = tblWarehouse.getValueAt(r, 2).toString();
            String warehouse = tblWarehouse.getValueAt(r, 0).toString();
            new WarehouseUpdate(id,name,type,warehouse).setVisible(true);
            ID = "";
        }
    }//GEN-LAST:event_btnEditInfoActionPerformed

    private void btnRefreshClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshClientsActionPerformed
        String sql1 = "SELECT WarehouseName,CONCAT('$ ', FORMAT(Price,0)),Type,Quantity,Name,ID FROM material";
        g.fillToJTable(sql1, tblWarehouse);
        txtSearch.requestFocus();
    }//GEN-LAST:event_btnRefreshClientsActionPerformed

    private void cmbWarehouseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWarehouseItemStateChanged
        
        //String empty = ((JTextComponent)cmbWarehouse.getEditor().getEditorComponent()).getText();
        switch (cmbWarehouse.getSelectedIndex()) 
        {
            case 0:
                //filter("");
                g.fillToJTable("SELECT WarehouseName,CONCAT('$ ',FORMAT(Price,0)),Type,Quantity,Name,ID FROM material",tblWarehouse);
                break;
            case 1:
                {
                    //filter("0");
                    g.fillToJTable("SELECT WarehouseName,CONCAT('$ ',FORMAT(Price,0)),Type,Quantity,Name,ID FROM material WHERE Quantity <5 And Quantity>0", tblWarehouse);
                    //filter("[1-4]?");
                }
                break;

            case 2:
                //filter("0");
                g.fillToJTable("SELECT WarehouseName,CONCAT('$ ',FORMAT(Price,0)),Type,Quantity,Name,ID FROM material WHERE Quantity = 0", tblWarehouse);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cmbWarehouseItemStateChanged

    private void cmbWarehouseNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbWarehouseNameFocusGained
        
    }//GEN-LAST:event_cmbWarehouseNameFocusGained

    private void cmbWarehouseNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWarehouseNameItemStateChanged
        //String warehouse = ((JTextComponent)cmbWarehouseName.getEditor().getEditorComponent()).getText();
        String warehouse = cmbWarehouseName.getSelectedItem().toString();
        if(warehouse.equals("جميع المخازن"))
        {
            filter("");
        }
        else
        {
            filter(warehouse);
        }
       
    }//GEN-LAST:event_cmbWarehouseNameItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warehouse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warehouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEditInfo;
    private javax.swing.JButton btnRefreshClients;
    private javax.swing.JComboBox<String> cmbWarehouse;
    private javax.swing.JComboBox<String> cmbWarehouseName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWarehouse;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
